---
# source: https://medium.com/codenx/containerizing-net-core-applications-with-docker-and-orchestrating-with-kubernetes-e67ce1715ec7
apiVersion: v1
kind: Service
metadata:
  name: assignment2-service
spec:
  selector:
    app: assignment2
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer